import time
import random
input("Enter hwid: ") 
print("Welcome!") 
time.sleep(3) 
ch1 = input("IP: ") 
input ("Port: ") 
print("Send packet to " +str(ch1) + " 129bytes") 
time.sleep("2) 
print("Send packet to " +str(ch1) + " 129bytes") 
time.sleep("2) 
print("Send packet to " +str(ch1) + " 129bytes") 
time.sleep("2) 
print("Send packet to " +str(ch1) + " 129bytes") 
time.sleep("2) 
print("Send packet to " +str(ch1) + " 129bytes") 
time.sleep("2) 
print("Send packet to " +str(ch1) + " 129bytes") 
time.sleep("2) 
print("Send packet to " +str(ch1) + " 129bytes") 
time.sleep("2) 
print("Send packet to " +str(ch1) + " 129bytes") 
time.sleep("2) 
print("Send packet to " +str(ch1) + " 129bytes") 
time.sleep("2) 
print("Send packet to " +str(ch1) + " 129bytes") 
time.sleep("2) 
print("Send packet to " +str(ch1) + " 129bytes") 
time.sleep("2) 
print("Send packet to " +str(ch1) + " 129bytes") 
time.sleep("2) 
print("DoS attack ended") 
